from app.connectors.database_connector import Base
from .user import User
from .syllabus import Syllabus
from .batch import Batch
from .student import Student
from .batch_student import BatchStudent
from .class_schedule import ClassSchedule
from .mentor import MentorProfile
from .guest import Guest
