"""add name to batch

Revision ID: 29a5b25c60e2
Revises: 767c33200c1b
Create Date: 2026-02-06 14:23:51.144755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29a5b25c60e2'
down_revision = '767c33200c1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batches', 'name')
    # ### end Alembic commands ###
