"""Fix class_schedules batch_id and day types

Revision ID: be0167aece7c
Revises: 95ff060d7160
Create Date: 2026-01-22 15:54:03.753813

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "be0167aece7c"
down_revision = "95ff060d7160"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "class_schedules",
        "batch_id",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        nullable=False,
        postgresql_using="batch_id::integer",
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "class_schedules",
        "day",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(length=10),
    )

    # ### end Alembic commands ###
