INVALID_SCHEMA = "INVALID_SCHEMA"
PUBLIC_SCHEMA = "public"
DB_NOT_UPTODATE = "DB_NOT_UPTODATE"
HEAD = "HEAD"
AUTHORIZATION = "Authorization"
INVALID_NOTIFICATION_TYPE = "INVALID_NOTIFICATION_TYPE"
TEMPLATE_FOLDER_NAME = "templates"
ATTACHMENT_FOLDER_NAME = "attachments"
TEMPLATE_FILE_EXTENTION = ".html.jinja"
INVALID_TOKEN = "INVALID_TOKEN"
UPDATED_AT = "updated_at"
COLUMN_NOT_FOUND = "COLUMN_NOT_FOUND"

# USER MANAGEMENT SERVICE RELATED CONSTANTS:
INCORRECT_PASSWORD = "INCORRECT_PASSWORD"
USER_CREATED_SUCCESSFULLY = "USER_CREATED_SUCCESSFULLY"
USER_NOT_FOUND = "USER_NOT_FOUND"
EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
PHONE_NUMBER_ALREADY_EXISTS = "PHONE_NUMBER_ALREADY_EXISTS"
USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
USER_REGISTERED_SUCCESSFULLY = "USER_REGISTERED_SUCCESSFULLY"

# SYLLABUS SERVICE RELATED CONSTANTS:
SYLLABUS_CREATED_SUCCESSFULLY = "SYLLABUS_CREATED_SUCCESSFULLY"
SYLLABUS_UPDATED_SUCCESSFULLY = "SYLLABUS_UPDATED_SUCCESSFULLY"
SYLLABUS_DELETED_SUCCESSFULLY = "SYLLABUS_DELETED_SUCCESSFULLY"
SYLLABUS_NAME_ALREADY_EXISTS = "SYLLABUS_NAME_ALREADY_EXISTS"
SYLLABUS_NOT_FOUND = "SYLLABUS_NOT_FOUND"
ONE_OR_MORE_SYLLABUS_NOT_FOUND = "ONE_OR_MORE_SYLLABUS_NOT_FOUND"

# BATCH SERVICE RELATED CONSTANTS:
BATCH_CREATED_SUCCESSFULLY = "BATCH_CREATED_SUCCESSFULLY"
BATCH_UPDATED_SUCCESSFULLY = "BATCH_UPDATED_SUCCESSFULLY"
BATCH_DELETED_SUCCESSFULLY = "BATCH_DELETED_SUCCESSFULLY"
BATCH_NOT_FOUND = "BATCH_NOT_FOUND"
CLASS_SCHEDULE_CREATED_SUCCESSFULLY = "CLASS_SCHEDULE_CREATED_SUCCESSFULLY"
CLASS_SCHEDULE_UPDATED_SUCCESSFULLY = "CLASS_SCHEDULE_UPDATED_SUCCESSFULLY"
CLASS_SCHEDULE_DELETED_SUCCESSFULLY = "CLASS_SCHEDULE_DELETED_SUCCESSFULLY"
CLASS_SCHEDULE_NOT_FOUND = "CLASS_SCHEDULE_NOT_FOUND"

# STUDENT SERVICE RELATED CONSTANTS:
STUDENT_CREATED_SUCCESSFULLY = "STUDENT_CREATED_SUCCESSFULLY"
STUDENT_UPDATED_SUCCESSFULLY = "STUDENT_UPDATED_SUCCESSFULLY"
STUDENT_DELETED_SUCCESSFULLY = "STUDENT_DELETED_SUCCESSFULLY"
STUDENT_NOT_FOUND = "STUDENT_NOT_FOUND"
STUDENT_DETAILS_ALREADY_EXISTS = "STUDENT_DETAILS_ALREADY_EXISTS"
STUDENT_BATCH_DETAILS_CREATED_SUCCESSFULLY = (
    "STUDENT_BATCH_DETAILS_CREATED_SUCCESSFULLY"
)
STUDENT_BATCH_DETAILS_UPDATED_SUCCESSFULLY = (
    "STUDENT_BATCH_DETAILS_UPDATED_SUCCESSFULLY"
)
STUDENT_BATCH_DETAILS_DELETED_SUCCESSFULLY = (
    "STUDENT_BATCH_DETAILS_DELETED_SUCCESSFULLY"
)
MAPPING_NOT_FOUND = "MAPPING_NOT_FOUND"
STUDENT_ALREADY_EXISTS_IN_THE_BATCH = "STUDENT_ALREADY_EXISTS_IN_THE_BATCH"
SCHEDULE_FOR_THIS_DAY_ALREADY_EXISTS_FOR_THIS_BATCH = (
    "SCHEDULE_FOR_THIS_DAY_ALREADY_EXISTS_FOR_THIS_BATCH"
)


# ┌────────────────────────────── FIELD VALIDATION ERROR MESSAGES ────────────────────────────────────┐

ATLEAST_ONE_UPPER_CASE = "must contain at least one uppercase letter."
ATLEAST_ONE_LOWER_CASE = "must contain at least one lowercase letter."
ATLEAST_ONE_DIGIT = "must contain at least one digit."
ATLEAST_ONE_SPECIAL_CHARACTER = "must contain at least one special character."
SHOULD_NOT_CONTAIN_SPACES = "must not contain spaces."


RESET_TOKEN_EXPIRED = "Reset token expired"
INVALID_RESET_TOKEN = "Invalid reset token"
PASSWORD_RESET_SUCCESSFULLY = "Password reset successfully"
PASSWORD_RESET_LINK_SENT = "Password reset link sent successfully"
